src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Json;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Nom d'utilisateur est nécessaire")]
    #[Assert\Length([
        'min' => 5,
        'max' => 20,
        'minMessage' => "Votre nom doit être au moins {{ limit }} characters long",
        'maxMessage' => "Votre nom ne peut pas dépasser {{ limit }} characters"
    ])]
    private ?string $username = null;

    #[ORM\Column(length: 191)]
    #[Assert\NotBlank(message:"Email est nécessaire")]
    #[Assert\Email(message:"The email '{{ value }}' is not a valid email ")]
    #[Assert\Length([
        'min' => 5,
        'max' => 40,
        'minMessage' => "Votre email doit être au moins {{ limit }} characters long",
        'maxMessage' => "Votre email ne peut pas dépasser {{ limit }} characters"
    ])]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Le téléphone est requis")]
    #[Assert\Length([
              'min' => 8,
              'max' => 8,
              'minMessage' => "Votre Numero de telephone doit être {{ limit }} characters long",
              'maxMessage' => "Votre Numero de telephone doit être {{ limit }} characters"
    ])]
    private ?string $numTel = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Mot de passe requis")]
    #[Assert\Length([
        'min' => 5,
        'max' => 10,
        'minMessage' => "Votre mot de passe doit être au moins {{ limit }} characters long",
        'maxMessage' => "Votre mot de passe ne peut pas dépasser {{ limit }} characters"
    ])]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 100)]
    private ?string $resetToken = null;

    #[ORM\Column]
    private ?bool $is_verified = false;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Addresse est requis")]
    #[Assert\Length([
        'min' => 5,
        'max' => 100,
        'minMessage' => "Votre addresse doit être au moins {{ limit }} characters long",
        'maxMessage' => "Votre nom ne peut pas dépasser {{ limit }} characters"
    ])]
    private ?string $fullAddress = null;

    #[ORM\Column(nullable: true)]
    private ?bool $etat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->numTel;
    }

    public function setNumTel(string $numTel): self
    {
        $this->numTel = $numTel;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt()
    {
        return \null;
    }

    public function eraseCredentials(){
        return null;
    }
    
    public function getUserIdentifier(){
        return $this->email;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getFullAddress(): ?string
    {
        return $this->fullAddress;
    }

    public function setFullAddress(string $fullAddress): self
    {
        $this->fullAddress = $fullAddress;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(?bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{

    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        
         if ($this->getUser()) {
            
            if(!$this->getUser()->getIsVerified()){
                $this->addFlash(
                    'Danger',
                    'Le compte est non vérifie ! veuillez vérifier votre boîte de réception !'
                );
                // get the login error if there is one
                $error = $authenticationUtils->getLastAuthenticationError();
                // last username entered by the user
                $lastUsername = $authenticationUtils->getLastUsername();

                //return $this->redirectToRoute('app_logout');

                return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
            }else{
                if (!$this->getUser()->getEtat()) {
                    $this->addFlash(
                        'Danger',
                        'Vous ete bloqué !'
                    );
                    // get the login error if there is one
                    $error = $authenticationUtils->getLastAuthenticationError();
                    // last username entered by the user
                    $lastUsername = $authenticationUtils->getLastUsername();
    
                    //return $this->redirectToRoute('app_logout');
    
                    return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
             }else{
                $this->addFlash(
                    'Succes',
                    'Seccuss !'
                );
                return $this->redirectToRoute('app_front');
             }
            }
             
         } 
          // get the login error if there is one
          $error = $authenticationUtils->getLastAuthenticationError();
          // last username entered by the user
          $lastUsername = $authenticationUtils->getLastUsername();

          return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    

}

templates/security/login.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Connexion{% endblock %}

{% block body %}

<body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <div class="pt-1 pb-1">
                    <h4 class="card-title text-center pb-1 fs-2" style="color:#ffc800;"><i>AURORA<i></h4>
                  </div>
            </div>
        </nav>


        
            <!-- Masthead-->
            <header class="masthead">
                <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 d-flex flex-column align-items-center justify-content-center">

                

              <div class="containerr">

                <div class="card-body">

                  <div class="pt-4 pb-1">
                    <h5 class="card-title text-center pb-2 fs-1" style="color:white;">Connectez-vous à votre compte</h5>
                    <p class="text-center pb-4 fs-6" style="color:white;">Entrer votre Email &amp; mot de passe pour se connecter</p>
                  </div>

                  <form class="row g-3 needs-validation" novalidate="" method="post">
                  
                        {% if error %}
                            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                        {% endif %}

                        {% if app.user and app.user.isVerified == false %}
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" 
                            aria-label="close"></button>
                            <div class="alert-message">
                                <strong>Votre compte n'est pas activé </strong>, 
                                <a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
                            </div>
                        </div>
                        {% endif %}
                        {% if app.user and app.user.isVerified == true  and app.user.etat == true %}
                            <div class="alert alert-success alert-dismissible" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert" 
                                aria-label="close"></button>
                                <div class="alert-message">
                                    <strong>Votre compte est activé </strong>
                                </div>
                            </div>
                        {% endif %}

                        {% for message in app.flashes('Success') %}
                            <div class="alert alert-success">
                                {{ message }}
                            </div>
                        {% endfor %}
                        {% for message in app.flashes('Warning') %}
                            <div class="alert alert-warning">
                                {{ message }}
                            </div>
                        {% endfor %}
                        {% for message in app.flashes('Danger') %}
                            <div class="alert alert-danger">
                                {{ message }}
                            </div>
                        {% endfor %}
                    <div class="col-12">
                      <label for="yourUsername" class="form-label" style="color:#ffc800;"><b>Email</b></label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="email" value="{{ last_username }}" placeholder="Exemple@gmail.com" style="text-align:center;" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
                        <div class="invalid-feedback">Veuillez saisir votre e-mail.</div>
                      </div>
                    </div>
                    
                    <div class="col-12">
                      <label for="yourPassword" class="form-label" style="color:#ffc800;" ><b>Password</b></label>
                      <input type="password" name="password" id="inputPassword" placeholder="********" style="text-align:center;" class="form-control" autocomplete="current-password" required>
                      <div class="invalid-feedback">s'il vous plait entrez votre mot de passe!</div>
                    </div>
                    <div class="col-12">
                    <input type="hidden" name="_csrf_token"
                        value="{{ csrf_token('authenticate') }}"
                    >
                    </div>

                    <div class="col-12" align="start" style="margin-left:20px;">
                      
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe" >
                        <label class="form-check-label" for="rememberMe" style="color:#ffc800;"><b>Je souhaite étre identifié automatiquement</b></label>
                      
                      </div>
                    
                    <div class="col-12">
                      <button class="btn btn-warning w-50" type="submit" style="color:white;"><b>Login</b></button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0" style="color:#ffc800;"><b>Tu n'a pas de compte ? </b><a href="{{ path('app_register')}}" style="color:white;"><b> Créer un compte !</b></a></p>
                    </div>
                    
                        <a href="{{ path('app_front') }}" align="start"><b>Retour à la page d'accueil</b></a>
                        <a href="{{ path('app_oublie_pass') }}" align="end"><b>Mot de passe oublié</b></a>
                  </form>

                </div>
              </div>


            </div>
          </div>
        </div>
        
            

                
           

        
        
        </header>
        
    
       
        
    </body>

{% endblock %}

templates/security/reset_password.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Réanitialisation de mot de passe{% endblock %}

{% block body %}

<body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <div class="pt-1 pb-1">
                    <h4 class="card-title text-center pb-1 fs-2" style="color:#ffc800;"><i>AURORA<i></h4>
                  </div>
            </div>
        </nav>


        
        <!-- Masthead-->
        <header class="masthead">

        <div class="container">
          <div class="row justify-content-center">
            
<div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">

              
              <div class="containerr ">

                <div class="card-body">
              
             <h1>Réanitialisation de mot de passe</h1>
             <br>
             <br>
            {{ form_start(passForm) }}
                <div class="col-12">
                    <label for="yourPassword" class="form-label" style="color:#ffc800;"><b>Entrer votre Mot de passe</b></label>
                    {{ form_widget(passForm.password.first,{'attr':{'class':'form-control'}}) }}
                    <div class="invalid-feedback">S'il vous plait entrez votre mot de passe !</div>
                    </div>
                {{ form_errors(passForm.password,{'attr':{'class':'text-danger'}}) }}
                  <br>
                  <div class="col-12">
                  <label for="yourPassword" class="form-label" style="color:#ffc800;"><b>Confirmation votre mot de passe</b></label>
                  {{ form_widget(passForm.password.second,{'attr':{'class':'form-control'}}) }} 
                  </div>
                  <br>
                <button class="btn btn-warning w-50" type="submit" style="color:white;">réinitialiser le mot de passe</button>
                <br>
                <br>
                <div class="col-12">
                <a href="{{ path('app_front') }}" align="start"><b>Retour à la page d'accueil</b></a>
                </div>
            {{ form_end(passForm) }}

            
          </div>
        </div>
        
            
</div>
        </div>
        </div>
                
           

        
        
        </header>
        
    
       
        
    </body>

{% endblock %}

templates/security/reset_password_request.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Réanitialisation de mot de passe{% endblock %}

{% block body %}

<body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <div class="pt-1 pb-1">
                    <h4 class="card-title text-center pb-1 fs-2" style="color:#ffc800;"><i>AURORA<i></h4>
                  </div>
            </div>
        </nav>


        
        <!-- Masthead-->
        <header class="masthead">

        <div class="container">
          <div class="row justify-content-center">
            
        <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">

              
              <div class="containerr ">

                <div class="card-body">
              
             <h1>Réanitialisation de mot de passe</h1>
             <br>
             <br>
            {{ form_start(requestPassForm) }}

                <div class="col-12">
                    <label for="yourEmail" class="form-label" style="color:#ffc800;"><b>Entrer votre e-mail</b></label>
                    {{ form_widget(requestPassForm.email,{'attr':{'class':'form-control'}}) }}
                    </div>
                    {{ form_errors(requestPassForm.email,{'attr':{'class':'text-danger'}}) }}
                <br>
                <button class="btn btn-warning w-50" type="submit" style="color:white;">Envoyer</button>
                <br>
                <br>
                <div class="col-12">
                <a href="{{ path('app_front') }}" align="start"><b>Retour à la page d'accueil</b></a>
                </div>
            {{ form_end(requestPassForm) }}

            
          </div>
        </div>
        
            

            </div>
          </div>
        </div>    
           

        
        
        </header>
        
    
       
        
    </body>

{% endblock %}